/*
 * This file is generated by jOOQ.
 */
package com.customer.profile.common.entities.tables.records;


import com.customer.profile.common.entities.tables.Customer;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record12<Integer, String, String, String, String, String, String, LocalDateTime, String, Integer, String, JSON> {

    private static final long serialVersionUID = -710132266;

    /**
     * Setter for <code>customer_portal.customer.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer_portal.customer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>customer_portal.customer.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer_portal.customer.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customer_portal.customer.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer_portal.customer.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>customer_portal.customer.middle_name</code>.
     */
    public void setMiddleName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>customer_portal.customer.middle_name</code>.
     */
    public String getMiddleName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>customer_portal.customer.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>customer_portal.customer.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>customer_portal.customer.address_1</code>.
     */
    public void setAddress_1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>customer_portal.customer.address_1</code>.
     */
    public String getAddress_1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>customer_portal.customer.address_2</code>.
     */
    public void setAddress_2(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>customer_portal.customer.address_2</code>.
     */
    public String getAddress_2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>customer_portal.customer.dob</code>.
     */
    public void setDob(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>customer_portal.customer.dob</code>.
     */
    public LocalDateTime getDob() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>customer_portal.customer.gender</code>.
     */
    public void setGender(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>customer_portal.customer.gender</code>.
     */
    public String getGender() {
        return (String) get(8);
    }

    /**
     * Setter for <code>customer_portal.customer.mobile</code>.
     */
    public void setMobile(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>customer_portal.customer.mobile</code>.
     */
    public Integer getMobile() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>customer_portal.customer.pan_number</code>.
     */
    public void setPanNumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>customer_portal.customer.pan_number</code>.
     */
    public String getPanNumber() {
        return (String) get(10);
    }

    /**
     * Setter for <code>customer_portal.customer.address_proof</code>.
     */
    public void setAddressProof(JSON value) {
        set(11, value);
    }

    /**
     * Getter for <code>customer_portal.customer.address_proof</code>.
     */
    public JSON getAddressProof() {
        return (JSON) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, String, String, String, String, LocalDateTime, String, Integer, String, JSON> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, String, String, String, String, LocalDateTime, String, Integer, String, JSON> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customer.CUSTOMER.ID;
    }

    @Override
    public Field<String> field2() {
        return Customer.CUSTOMER.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return Customer.CUSTOMER.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Customer.CUSTOMER.MIDDLE_NAME;
    }

    @Override
    public Field<String> field5() {
        return Customer.CUSTOMER.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return Customer.CUSTOMER.ADDRESS_1;
    }

    @Override
    public Field<String> field7() {
        return Customer.CUSTOMER.ADDRESS_2;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Customer.CUSTOMER.DOB;
    }

    @Override
    public Field<String> field9() {
        return Customer.CUSTOMER.GENDER;
    }

    @Override
    public Field<Integer> field10() {
        return Customer.CUSTOMER.MOBILE;
    }

    @Override
    public Field<String> field11() {
        return Customer.CUSTOMER.PAN_NUMBER;
    }

    @Override
    public Field<JSON> field12() {
        return Customer.CUSTOMER.ADDRESS_PROOF;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getMiddleName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getAddress_1();
    }

    @Override
    public String component7() {
        return getAddress_2();
    }

    @Override
    public LocalDateTime component8() {
        return getDob();
    }

    @Override
    public String component9() {
        return getGender();
    }

    @Override
    public Integer component10() {
        return getMobile();
    }

    @Override
    public String component11() {
        return getPanNumber();
    }

    @Override
    public JSON component12() {
        return getAddressProof();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getMiddleName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getAddress_1();
    }

    @Override
    public String value7() {
        return getAddress_2();
    }

    @Override
    public LocalDateTime value8() {
        return getDob();
    }

    @Override
    public String value9() {
        return getGender();
    }

    @Override
    public Integer value10() {
        return getMobile();
    }

    @Override
    public String value11() {
        return getPanNumber();
    }

    @Override
    public JSON value12() {
        return getAddressProof();
    }

    @Override
    public CustomerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CustomerRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public CustomerRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CustomerRecord value4(String value) {
        setMiddleName(value);
        return this;
    }

    @Override
    public CustomerRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public CustomerRecord value6(String value) {
        setAddress_1(value);
        return this;
    }

    @Override
    public CustomerRecord value7(String value) {
        setAddress_2(value);
        return this;
    }

    @Override
    public CustomerRecord value8(LocalDateTime value) {
        setDob(value);
        return this;
    }

    @Override
    public CustomerRecord value9(String value) {
        setGender(value);
        return this;
    }

    @Override
    public CustomerRecord value10(Integer value) {
        setMobile(value);
        return this;
    }

    @Override
    public CustomerRecord value11(String value) {
        setPanNumber(value);
        return this;
    }

    @Override
    public CustomerRecord value12(JSON value) {
        setAddressProof(value);
        return this;
    }

    @Override
    public CustomerRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, String value9, Integer value10, String value11, JSON value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Integer id, String email, String firstName, String middleName, String lastName, String address_1, String address_2, LocalDateTime dob, String gender, Integer mobile, String panNumber, JSON addressProof) {
        super(Customer.CUSTOMER);

        set(0, id);
        set(1, email);
        set(2, firstName);
        set(3, middleName);
        set(4, lastName);
        set(5, address_1);
        set(6, address_2);
        set(7, dob);
        set(8, gender);
        set(9, mobile);
        set(10, panNumber);
        set(11, addressProof);
    }
}
