/*
 * This file is generated by jOOQ.
 */
package com.customer.profile.common.entities;


import com.customer.profile.common.entities.tables.Customer;
import com.customer.profile.common.entities.tables.Roles;
import com.customer.profile.common.entities.tables.UserRoles;
import com.customer.profile.common.entities.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerPortal extends SchemaImpl {

    private static final long serialVersionUID = 1622412746;

    /**
     * The reference instance of <code>customer_portal</code>
     */
    public static final CustomerPortal CUSTOMER_PORTAL = new CustomerPortal();

    /**
     * The table <code>customer_portal.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>customer_portal.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>customer_portal.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>customer_portal.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private CustomerPortal() {
        super("customer_portal", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            Roles.ROLES,
            UserRoles.USER_ROLES,
            Users.USERS);
    }
}
