/*
 * This file is generated by jOOQ.
 */
package com.customer.profile.common.entities;


import com.customer.profile.common.entities.tables.Customer;
import com.customer.profile.common.entities.tables.Roles;
import com.customer.profile.common.entities.tables.UserRoles;
import com.customer.profile.common.entities.tables.Users;
import com.customer.profile.common.entities.tables.records.CustomerRecord;
import com.customer.profile.common.entities.tables.records.RolesRecord;
import com.customer.profile.common.entities.tables.records.UserRolesRecord;
import com.customer.profile.common.entities.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>customer_portal</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomerRecord, Integer> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
    public static final Identity<RolesRecord, Long> IDENTITY_ROLES = Identities0.IDENTITY_ROLES;
    public static final Identity<UsersRecord, Long> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = UniqueKeys0.KEY_CUSTOMER_PRIMARY;
    public static final UniqueKey<RolesRecord> KEY_ROLES_PRIMARY = UniqueKeys0.KEY_ROLES_PRIMARY;
    public static final UniqueKey<RolesRecord> KEY_ROLES_UK_NB4H0P6TXRMFC0XBRD1KGLP9T = UniqueKeys0.KEY_ROLES_UK_NB4H0P6TXRMFC0XBRD1KGLP9T;
    public static final UniqueKey<UserRolesRecord> KEY_USER_ROLES_PRIMARY = UniqueKeys0.KEY_USER_ROLES_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_UK_SX468G52BPETVLAD2J9Y0LPTC = UniqueKeys0.KEY_USERS_UK_SX468G52BPETVLAD2J9Y0LPTC;
    public static final UniqueKey<UsersRecord> KEY_USERS_UKFNRANLQHUBVW04BOOPN028E6 = UniqueKeys0.KEY_USERS_UKFNRANLQHUBVW04BOOPN028E6;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserRolesRecord, UsersRecord> FKHFH9DX7W3UBF1CO1VDEV94G3F = ForeignKeys0.FKHFH9DX7W3UBF1CO1VDEV94G3F;
    public static final ForeignKey<UserRolesRecord, RolesRecord> FKH8CIRAMU9CC9Q3QCQIV4UE8A6 = ForeignKeys0.FKH8CIRAMU9CC9Q3QCQIV4UE8A6;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CustomerRecord, Integer> IDENTITY_CUSTOMER = Internal.createIdentity(Customer.CUSTOMER, Customer.CUSTOMER.ID);
        public static Identity<RolesRecord, Long> IDENTITY_ROLES = Internal.createIdentity(Roles.ROLES, Roles.ROLES.ID);
        public static Identity<UsersRecord, Long> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = Internal.createUniqueKey(Customer.CUSTOMER, "KEY_customer_PRIMARY", new TableField[] { Customer.CUSTOMER.ID }, true);
        public static final UniqueKey<RolesRecord> KEY_ROLES_PRIMARY = Internal.createUniqueKey(Roles.ROLES, "KEY_roles_PRIMARY", new TableField[] { Roles.ROLES.ID }, true);
        public static final UniqueKey<RolesRecord> KEY_ROLES_UK_NB4H0P6TXRMFC0XBRD1KGLP9T = Internal.createUniqueKey(Roles.ROLES, "KEY_roles_UK_nb4h0p6txrmfc0xbrd1kglp9t", new TableField[] { Roles.ROLES.NAME }, true);
        public static final UniqueKey<UserRolesRecord> KEY_USER_ROLES_PRIMARY = Internal.createUniqueKey(UserRoles.USER_ROLES, "KEY_user_roles_PRIMARY", new TableField[] { UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE_ID }, true);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", new TableField[] { Users.USERS.ID }, true);
        public static final UniqueKey<UsersRecord> KEY_USERS_UK_SX468G52BPETVLAD2J9Y0LPTC = Internal.createUniqueKey(Users.USERS, "KEY_users_UK_sx468g52bpetvlad2j9y0lptc", new TableField[] { Users.USERS.EMAIL }, true);
        public static final UniqueKey<UsersRecord> KEY_USERS_UKFNRANLQHUBVW04BOOPN028E6 = Internal.createUniqueKey(Users.USERS, "KEY_users_UKfnranlqhubvw04boopn028e6", new TableField[] { Users.USERS.USERNAME, Users.USERS.EMAIL }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserRolesRecord, UsersRecord> FKHFH9DX7W3UBF1CO1VDEV94G3F = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, UserRoles.USER_ROLES, "FKhfh9dx7w3ubf1co1vdev94g3f", new TableField[] { UserRoles.USER_ROLES.USER_ID }, true);
        public static final ForeignKey<UserRolesRecord, RolesRecord> FKH8CIRAMU9CC9Q3QCQIV4UE8A6 = Internal.createForeignKey(Keys.KEY_ROLES_PRIMARY, UserRoles.USER_ROLES, "FKh8ciramu9cc9q3qcqiv4ue8a6", new TableField[] { UserRoles.USER_ROLES.ROLE_ID }, true);
    }
}
