/*
 * This file is generated by jOOQ.
 */
package com.customer.profile.common.entities;


import com.customer.profile.common.entities.tables.Customer;
import com.customer.profile.common.entities.tables.Roles;
import com.customer.profile.common.entities.tables.UserRoles;
import com.customer.profile.common.entities.tables.Users;


/**
 * Convenience access to all tables in customer_portal
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>customer_portal.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>customer_portal.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>customer_portal.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>customer_portal.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
